'use client';
import type { Metadata } from "next";
import { Geist, Geist_Mono, Sedan_SC, Mohave} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const sedanSC = Sedan_SC({
  variable: "--font-sedan-sc",
  subsets: ["latin"],
  weight: "400",
})

const mohave = Mohave({
  variable: "--font-mohave",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sedanSC.variable} ${mohave.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
